development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: g4up
  pool: 5
  socket: /tmp/.s.PGSQL.5432
  username: faerie
